[package]
name = "philososhark-rs"
version = "0.1.0"
authors = ["Ibrahim Hisham"]
edition = "2018"
[dependencies]
serenity = "0.10"
serde_json = "1.0.68"
rand = "0.8.4"
ferris-says = "0.2.1"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }